### ISSUE TITLE
Vec3 in elm-explorations/linear-algebra not parsed correctly

### ISSUE THREAD

**Issue by MartinSStewart** [kraklin/elm-debug-transformer#2]
The following code will print text to the console that won't be parsed. 
```
module Main exposing (main)

import Browser
import Html exposing (Html)
import Html.Events
import Math.Vector3 as Vec3


type Msg_
    = Msg_


type alias Model_ =
    { v : Vec3.Vec3
    }


main : Program () Model_ Msg_
main =
    Browser.sandbox
        { init =
            { v = Vec3.vec3 0 0 0
            }
        , view = \_ -> Html.button [ Html.Events.onClick Msg_ ] [ Html.text "click to print to console" ]
        , update = \_ model -> model |> Debug.log ""
        }
```

Also consider looking at the issues in elm-monitor.  It also uses Debug.log to improve debugging and probably has a number of bugs that might appear in your project as well. Here is the Vec3 issue for example https://github.com/layflags/elm-monitor/issues/11

**Comment by kraklin** [comment]
Hi @MartinSStewart. Thanks for the issue. Can you please try the version 0.0.6? It should be fixed now. Also thank you for pointing out the elm-monitor repository. It looks like it would be a good source of inspiration

**Comment by MartinSStewart** [comment]
It doesn't seem to work for me, using the example from before, I still get this 
![image](https://user-images.githubusercontent.com/5068391/59487371-c133d800-8e7c-11e9-9272-cf84841b23eb.png) as output.

**Comment by kraklin** [comment]
@MartinSStewart Good to hear that ;)
